export const SKILL_NODES = Object.freeze({
  normal: {
    id: 'normal',
    name: 'NORMAL',
    cost: 50,
    parents: [],
    children: ['rehearse', 'hold'],
    type: 'PASSIVE',
    meta: '+1 OVERLOAD LIMIT',
    description: 'Increase the Overload limit by 1.',
    position: { x: 50, y: 57 },
  },
  rehearse: {
    id: 'rehearse',
    name: 'REHEARSE',
    cost: 175,
    parents: ['normal'],
    children: ['plan'],
    type: 'GETTING READY',
    meta: 'ADDS 5 SEC',
    description: 'Finish the rehearsal to gain +1 Overload limit for this run. A wrong answer or timeout spawns 2 minigames.',
    position: { x: 31, y: 37 },
  },
  hold: {
    id: 'hold',
    name: 'HOLD',
    cost: 225,
    parents: ['normal'],
    children: ['adrenaline'],
    type: 'AUTOMATIC',
    meta: 'ONCE PER RUN',
    description: 'Hold back the first minigame that would fill the last open Overload slot. It spawns when a slot opens or after 5 seconds.',
    position: { x: 69, y: 37 },
  },
  plan: {
    id: 'plan',
    name: 'PLAN',
    cost: 325,
    parents: ['rehearse'],
    children: [],
    type: 'GETTING READY',
    meta: 'ADDS 4 SEC',
    description: 'Finish the sequence to stagger the next 2 double spawns. The second minigame spawns 3 seconds later.',
    position: { x: 18, y: 16 },
  },
  adrenaline: {
    id: 'adrenaline',
    name: 'ADRENALINE',
    cost: 425,
    parents: ['hold'],
    children: ['suppress'],
    type: 'AUTOMATIC',
    meta: 'ONCE PER RUN',
    description: 'At 1 below the Overload limit, stop new minigames from spawning for 6 seconds. Active minigames stay on screen.',
    position: { x: 82, y: 16 },
  },
  suppress: {
    id: 'suppress',
    name: 'SUPPRESS',
    cost: 650,
    parents: ['adrenaline'],
    children: [],
    type: 'AUTOMATIC',
    meta: 'ONCE PER RUN',
    description: 'When you would Overload, mash Space to suppress half of the active minigames. Suppressed minigames do not count as cleared.',
    position: { x: 91, y: 53 },
  },
})

export const SKILL_NODE_LIST = Object.freeze(Object.values(SKILL_NODES))
export const STARTING_NODE_ID = 'normal'
